# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["PROG7311 POE P2/PROG7311 POE P2.csproj", "PROG7311 POE P2/"]
COPY ["Web_API/Web_API.csproj", "Web_API/"]


RUN dotnet restore "PROG7311 POE P2/PROG7311 POE P2.csproj"

COPY . .

WORKDIR "/src/PROG7311 POE P2"
RUN dotnet build "PROG7311 POE P2.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release

RUN dotnet publish "PROG7311 POE P2.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false /p:ErrorOnDuplicatePublishOutputFiles=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PROG7311 POE P2.dll"]